name: Push to AWS ECR

on:
  push:
    branches: [master]

jobs:
    push-ids_collector:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: AWS Configure CLI
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-north-1

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1

          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              REPOSITORY: redflags
              IMAGE_TAG: latest
            run: |
              docker build -t container_flags /red_flags/scripts/cron_jobs/final_scripts_v2/
              docker tag container_flags:latest 654654334568.dkr.ecr.eu-north-1.amazonaws.com/container_flags:latest
              docker push 654654334568.dkr.ecr.eu-north-1.amazonaws.com/container_flags:latest