FROM public.ecr.aws/lambda/python:3.10

RUN pip3 install requests psycopg2-binary

COPY process_update.py ${LAMBDA_TASK_ROOT}
COPY flag_calculator.py ${LAMBDA_TASK_ROOT}
COPY table_update.py ${LAMBDA_TASK_ROOT}
COPY none_cases.py ${LAMBDA_TASK_ROOT}


CMD [ "process_update.main_process" ]